### ISSUE TITLE
local variable 'videoname' referenced before assignment

### ISSUE THREAD

**Issue by Kingtin** [cashiwamochi/RealEstate10K_Downloader#10]
After exec python3 generate_dataset.py train :

[INFO] Loading data list ... Done!
[INFO] 200 movies are used in train mode
[INFO] Start downloading 200 movies
[INFO] Downloading https://www.youtube.com/watch?v=KeXr_qWVbiU
Traceback (most recent call last):
File "generate_dataset.py", line 171, in 
isOK = downloader.Run()
File "generate_dataset.py", line 139, in Run
process(data, 0, videoname, self.output_root)
UnboundLocalError: local variable 'videoname' referenced before assignment

**Comment by greeneggsandyaml** [comment]
Hi, I encountered the same issue. Did you solve this?

**Comment by qsong2001** [comment]
Refer to 
https://github.com/cashiwamochi/RealEstate10K_Downloader/pull/9/commits/0512d22c20259609fea4c48f16965bc319ea3a80
