### ISSUE TITLE
How large is the training set of RealEstate10K dataset

### ISSUE THREAD

**Issue by phongnhhn92** [cashiwamochi/RealEstate10K_Downloader#6]
Hello, 
Thanks for your code ! I would like to ask the size of the training images after running your code thorugh the training set. you mentioned that is a huge number but would you share how much TB it would be. I am asking to buy additional hard drive for it.

**Comment by cashiwamochi** [comment]
Hello, phongnhhn92 san

I'm afraid to say that I couldn't answer the accurate size, and it depends on image size which you want to use in your training.
I think that 8TB is much enough, but if you want to know more accurate size, you should download 5 or 10% of the dataset.
This would enable you to estimate the size of the whole dataset.
Good luck in your research.

cashiwamochi

**Comment by phongnhhn92** [comment]
Thanks for your helpful reply !
I will close this for now :D
